### ISSUE TITLE
Please expose the pairing related methods in the Python API

### ISSUE THREAD

**Issue by zapta** [OpenBluetoothToolbox/python_simpleble#6]
These two pairing related methods are not reflected in the Python API.

Please add them there.

https://github.com/OpenBluetoothToolbox/SimpleBLE/blob/main/include/simpleble/Peripheral.h#L32

**Comment by kdewald** [comment]
Hey @zapta, thanks for the report!

I'll upgrade SimplePyBLE to use the latest build of master of SimpleBLE with those new functions (which is a preview of v0.4.0). I still need to finish a few details of that release to be sure everything works as expected, but as soon as that one is out, I'll also release a new version of SimplePyBLE.

**Comment by kdewald** [comment]
If you need to use the library before I'm ready, I'd recommend building from source.

**Comment by kdewald** [comment]
Ok, `main` has been updated. I'll make sure everything is building fine for al OSs and I'll probably do a partial release.
