### ISSUE TITLE
peripheral.identifier() in the scan example always return an empty string.

### ISSUE THREAD

**Issue by zapta** [OpenBluetoothToolbox/python_simpleble#7]
I am running the scan.py example on windows 10 pro, Python 3.9.5. Everything works well except that the device names are not printed. I think it's supposed to come from peripheral.identifier() but it seems to return an empty string for all devices.

By device name I mean the human friendly name that we see in the bluetooth device setting screens of Windows, iPhone, etc.

**Comment by kdewald** [comment]
Hey @zapta, thanks for the report!

There's a chance this might be an old bug present in SimpleBLE v0.2.0. I just updated `main` to use the release candidate for v0.4.0, which should fix a whole bunch of issues, as well as adding a lot of the missing functionality that hadn't been ported over.

Can you run this with the latest build and tell me if it works or not?

**Comment by zapta** [comment]
Thanks @kdewald. Does it mean that if I will run 'pip install simplepyble' I will get the new version?

**Comment by zapta** [comment]
.. or pip update, if there is such a thing.

**Comment by kdewald** [comment]
I just launched the formal release to PyPi, once it's done I'll confirm the command.

**Comment by kdewald** [comment]
@zapta https://pypi.org/project/simplepyble/0.0.5.dev0/
